### ISSUE TITLE
The End Dimension Bug

### ISSUE THREAD

**Issue by Yuppitt** [tristankechlo/Explorations#1]
I encountered a bug where the game will crash trying to enter the end while using this mod in a modpack but to verify that it was explorations that caused this bug I tried the same on a single player world where this was the only mod installed and the same issue was present.

1. create or find an end portal.
2. once you attempt to light the portal then enter the end the game will crash.

Though interestingly if you enter the end before the mod is installed then you leave and install it then join the world again the game will not crash. I think the issue specifically occurs while attempting to generate the end. (The issue is also not present for the other vanilla dimensions.)

**Comment by tristankechlo** [comment]
Which minecraft version are you using?
Do you have a crashlog?
I think this problem will occur for dimensions from other mods too

**Comment by tristankechlo** [comment]
should be fixed now,
try the newest forge version and the newest mod version
