### ISSUE TITLE
Crash upon entering the End: bound must be greater than origin

### ISSUE THREAD

**Issue by Reshy** [tristankechlo/Explorations#2]
**Describe the bug**  
Game crashed upon entering the end.

**To Reproduce**  
1. Enter an End Portal.

**Expected behavior**  
End shouldn't crash upon entering the end.

**Additional context**  
Crash Log:  https://pastebin.com/dk9NuvQJ

**Comment by SargRReal** [comment]
yes i've experienced this too, thank you for reporting it first

**Comment by tristankechlo** [comment]
Thanks for reporting, will fix it soon

**Comment by tristankechlo** [comment]
This should be fixed with newest modversion 1.1.1
