### ISSUE TITLE
Config to turn off structures

### ISSUE THREAD

**Issue by Reshy** [tristankechlo/Explorations#3]
**Is your feature request related to a problem? Please describe.**  
The structures of the mod are all or nothing, you either take all of them or none of them, there's no way to toggle off specific structures.

**Describe the solution you'd like**  
It would be nice if there was an included config that controlled how often buildings spawn, with the option to turn them off entirely.  Some buildings may not be fitting for what a modpack has in mind.

**Comment by amidnightblue** [comment]
Yes please! I'd like to disable the floating islands and scarecrows or turn down the frequency of them. I'm finding way too many scarecrows in my Fabric 1.19.2 Terralith world.

**Comment by tristankechlo** [comment]
All aspects (spawnrate/biomes/etc.) of the mod can be changed with datapacks,  
not sure if I will implement extra config-logic

**Comment by amidnightblue** [comment]
Ok... how do we go about doing that? I know nothing about datapacks. I was hoping for a nice simple mod menu config lol

**Comment by tristankechlo** [comment]
So I made a datapack that stops the floating islands from generating.  
You can find it here https://github.com/tristankechlo/Datapacks  
The zip file is ready to use, and I might add more example datapacks in the future

**Comment by tristankechlo** [comment]
I will close this now, since I will probably not in the near future
