### ISSUE TITLE
[1.18.2]  Crash with Undergardens

### ISSUE THREAD

**Issue by Reshy** [tristankechlo/Explorations#5]
**Describe the bug**  
Explorations seems to be causing a crash when generating chunks in the Undergarden Dimension Mod.

**To Reproduce**  
1. Go to the Undergardens
2. High Chance of crashing if a structure generates.

**Expected behavior**  
Explorations shouldn't crash attempting to generate chunks in a different dimension.

**Additional context**  
Crash Log:  https://pastebin.com/cRTT3L5z
Annotated Log:  https://pastebin.com/y8YQuCBi

**Comment by tristankechlo** [comment]
Thanks for reporting, will be fixed soon

**Comment by tristankechlo** [comment]
should be fixed in modversion 1.5.1
