### ISSUE TITLE
[Bug]: Scarecrows spawn very frequently

### ISSUE THREAD

**Issue by chorbintime** [tristankechlo/Explorations#6]
### What happened?

Likely due to scarecrows being marked as Features instead of Structures, they spawn VERY frequently. There can be up to 5 scarecrows within the immediate vision of a player when they first create a world.

More information can be found here https://github.com/XxRexRaptorxX/Additional-Structures-Fabric/issues/6 (I reported this on the wrong github as both mods add scarecrows and Explorations only mentions scarecrows on the wiki)

### Minecraft Version

1.20.1

### Modversion

Latest version on both Forge & Fabric

### Modloader

Other

### Additional context

Happens on both Forge & Fabric
Modpacks are BMC4 and MMC4
More info can be found here https://github.com/XxRexRaptorxX/Additional-Structures-Fabric/issues/6

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
I made the scarecrows a feature, and not a structure, so they can spawn that often.  
I like to see them that often, that's why I will keep them spawn that often,  
but I consider making a datapack that reduces the spawnrate of them drastically, since other people seem to be annoyed by them too

**Comment by chorbintime** [comment]
They spawn literally everywhere, which seems like something a majority of players wouldn't like. We already have a datapack that removes the scarecrows completely  https://cdn.discordapp.com/attachments/1064320137735450694/1137657721257209866/scarecrow_deaderer.zip

**Comment by tristankechlo** [comment]
Drastically reduced the scarecrow spawnrate in the newest version (1.6.1)
If you want zero scarecrows, there is an official datapack that removes scarecrows from multiple mods, including Explorations
https://curseforge.com/minecraft/texture-packs/scarecrow-obliterator-datapack

**Comment by nvb-uy** [comment]
Official? I'm flattered!

**Comment by tristankechlo** [comment]
Yeah, I was thinking of creating a datapack myself, then I found that pack.
But mine would have been basically identical, so this is the 'official' one now 👍
