### ISSUE TITLE
[Bug][1.5.3]: Crash when generating new chunks

### ISSUE THREAD

**Issue by Satrapie** [tristankechlo/Explorations#7]
### What happened?

Describe the bug
Explorations on my multiplayer server causes crash when generating certain new chunks since the last update (1.5.3)
Removing the mod or downgrading to the previous version (1.5.2) prevents crashes from occurring

### Minecraft Version

1.20.1

### Modversion

explorations-forge-1.20.4-1.5.3.jar

### Modloader

Forge

### Additional context

[crash-2024-01-15_05.27.09-server.txt](https://github.com/tristankechlo/Explorations/files/13934883/crash-2024-01-15_05.27.09-server.txt)

### Before submitting

- [X] I tested that the problem is caused by this mod (the bug does not happen when removing this mod)
- [X] I checked that there are no similar posts (open or closed) related to the this problem

**Comment by tristankechlo** [comment]
Hi, thanks for reporting.  
Looks like the update isn't as backwards compatible as I thought.  
I will adjust the uploaded file so it's only available for Minecraft 1.20.4.  
Since there are no content changes with 1.5.3, you can continue to use modversion 1.5.2

**Comment by Satrapie** [comment]
Thank you for responding so quickly, I will therefore stay on the previous version!

**Comment by tristankechlo** [comment]
Adjusted the files on Curseforge and Modrinth, 1.5.3 now only available for minecraft 1.20.4.  
Closing this for now
